### ISSUE TITLE
The Visual Studio Code browser in Gitspaces failed to create

### ISSUE THREAD

**Issue by zyknow** [harness/harness#3594]
#### errorlog in Web
```
1 2024/12/2 22:42:12  Pulling image: mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04
2 2024/12/2 22:42:13  {"status":"Pulling from devcontainers/base","id":"dev-ubuntu-24.04"}
3 2024/12/2 22:42:13  {"status":"Digest: sha256:98575ffc6c65d3208a4f5856c2377668558d1dc01eb7e7fefdeb692532ebe85e"}
4 2024/12/2 22:42:13  {"status":"Status: Image is up to date for mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04"}
5 2024/12/2 22:42:13  Successfully pulled image
6 2024/12/2 22:42:13  Creating container: gitspace-harness-tradingviewnotice-rxq6b9
7 2024/12/2 22:42:14  Starting container: gitspace-harness-tradingviewnotice-rxq6b9
8 2024/12/2 22:42:14  Successfully started container
9 2024/12/2 22:42:14  Managing user output...
10 2024/12/2 22:42:14  Setting up user inside container
11 2024/12/2 22:42:14  Successfully setup user
12 2024/12/2 22:42:14  Setting up IDE inside container: vs_code_web
13 2024/12/2 22:42:16  Error while setting up IDE inside container: failed to copy media folder to container at path : error copying files to container: Error response from daemon: bad parameter: pathcannot be empty
```

#### errorlog in console
```
harness    | {"level":"error","error":"failed to resume start gitspace: couldn't call the agent start API: failed to start gitspace gitspace-harness-tradingviewnotice-rxq6b9: failed to setup IDE for gitspace gitspace-harness-tradingviewnotice-rxq6b9: failed to copy media folder to container at path : error copying files to container: Error response from daemon: bad parameter: pathcannot be empty","time":"2024-12-02T14:42:16.14165809Z","message":"error while handling gitspace infra event"}
```

#### docker-compose.yml
```
version: '3.9'
services:
  harness:
    image: harness/harness
    container_name: harness
    ports:
      - "31001:31000"
      - "31002:3022"
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/_system/Docker/Harness/data:/data
    environment:
      - GITNESS_DATABASE_DRIVER=postgres
      - GITNESS_DATABASE_DATASOURCE=*
      - GITNESS_PRINCIPAL_ADMIN_EMAIL=*@qq.com
      - GITNESS_PRINCIPAL_ADMIN_PASSWORD=*
      - GITNESS_HTTP_PORT=31000
      - GITNESS_URL_BASE=https://*:31000

      - GITNESS_URL_UI=https://*:31000
      # - GITNESS_URL_API=https://*:31000/api
      - GITNESS_URL_CONTAINER=https://*:31000
      - GITNESS_URL_GIT=https://*:31000/git
      - GITNESS_URL_REGISTRY=https://*:31000
      - GITNESS_URL_GIT_SSH=ssh://*:31002


      - GITNESS_HTTP_PROTO=https
      - GITNESS_URL_INTERNAL=https://*:31000
      - GITNESS_SSH_PORT=31002
      #- HTTP_PROXY=192.168.0.1:7893
      #- HTTPS_PROXY=192.168.0.1:7893
```

**Comment by dhruv-harness** [comment]
Hi @zyknow , first of all thanks for trying out gitspaces!

I was unable to replicate the issue. From the logs it looks like the selected IDE was not downloaded and installed properly.
Most likely, this could be a transient issue. Also I have pushed a small change to check this and handle this error gracefully. 

Can you please pull the harness/harness:latest again and try recreating the gitspace?

Regards
Dhruv

**Comment by zyknow** [comment]
Thank you for your reply @dhruv-harness. I pulled the latest harness and also deleted and re-pulled mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04, but I still get the same error. I don't know why. Is there anywhere else I can check for information?

**Comment by dhruv-harness** [comment]
Hi @zyknow , can you please share the details (OS, architecture, memory) of your system on which you are running the harness container? Also, can you please share the output of the `docker version` command?

Thanks and Regards
Dhruv

**Comment by zyknow** [comment]
Thank you for your response. Here is my system information. If you need any other information, please let me know.

* Total Memory: 31567.7 MB
* CPU:  Intel(R) Core(TM) i7-10700 CPU @ 2.90GHz

`uname -a`
```
Linux zy_nas 4.4.180+ #42218 SMP Mon Oct 18 19:17:56 CST 2021 x86_64 GNU/Linux synology_apollolake_918+
```

`docker version`
```
Client:
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.15.13
 Git commit:        b455053
 Built:             Thu Aug 19 07:13:24 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.15.13
  Git commit:       a3bc36f
  Built:            Thu Aug 19 07:11:25 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        ea3508454ff2268c32720eb4d2fc9816d6f75f88
 runc:
  Version:          v1.0.0-rc93
  GitCommit:        31cc25f16f5eba4d0f53e35374532873744f4b31
 docker-init:
  Version:          0.19.0
  GitCommit:        ed96d00
```

**Comment by dhruv-harness** [comment]
Thanks @zyknow for sharing this information. I dont think your setup is the issue here.

I am sure the problem is arising during the download and installation of code-server binary, which is used as the VSCode web IDE. Would it be possible for you to run a few commands and share their output? It would help us pinpoint the issue which is happening during the install.


1. Running a debug container
```
docker run --name debug-gitspace --detach --entrypoint "/bin/sh" mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04 -c "sleep infinity"
```
2. Execing into the container
```
docker exec -it debug-gitspace bash
```
3. Downloading and installing the code-server binary
```
curl -fsSL https://code-server.dev/install.sh | sh
```
4. Finding a specific path within the binary's install directory
```
echo "START_MARKER"$(find / -type d -path '*code-server/*src/browser/media*' -print -quit 2>/dev/null)"END_MARKER"
```
5. Running the binary
```
code-server
```

I am interested in the output of the 3rd, 4th and 5th commands.

Thanks and Regards
Dhruv

PS- We have a release planned which improves the visibility and handling for such scenarios. Your patience is much appreciated!

**Comment by zyknow** [comment]
```
root ➜ / $ curl -fsSL https://code-server.dev/install.sh | sh
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 5 ms: Couldn't connect to server
root ➜ / $ curl -fsSL https://code-server.dev/install.sh | sh
curl: (7) Failed to connect to raw.githubusercontent.com port 443 after 5 ms: Couldn't connect to server
root ➜ / $ export http_proxy="http://192.168.0.1:7893"
root ➜ / $ export https_proxy="http://192.168.0.1:7893"
root ➜ / $ curl -fsSL https://code-server.dev/install.sh | sh
Ubuntu 24.04.1 LTS
Installing v4.95.3 of the amd64 deb package from GitHub.

+ mkdir -p ~/.cache/code-server
+ curl -#fL -o ~/.cache/code-server/code-server_4.95.3_amd64.deb.incomplete -C - https://github.com/coder/code-server/releases/download/v4.95.3/code-server_4.95.3_amd64.deb
######################################################################## 100.0%
+ mv ~/.cache/code-server/code-server_4.95.3_amd64.deb.incomplete ~/.cache/code-server/code-server_4.95.3_amd64.deb
+ dpkg -i ~/.cache/code-server/code-server_4.95.3_amd64.deb
Selecting previously unselected package code-server.
(Reading database ... 20528 files and directories currently installed.)
Preparing to unpack .../code-server_4.95.3_amd64.deb ...
Unpacking code-server (4.95.3) ...
Setting up code-server (4.95.3) ...

deb package has been installed.

To have systemd start code-server now and restart on boot:
  sudo systemctl enable --now code-server@$USER
Or, if you don't want/need a background service you can run:
  code-server

root ➜ / $ echo "START_MARKER"$(find / -type d -path '*code-server/*src/browser/media*' -print -quit 2>/dev/null)"END_MARKER"R"/ $ echo "START_MARKER"$(find / -type d -path '*code-server/*src/browser/media*' -print -quit 2>/dev/null)"END_M
START_MARKER/usr/lib/code-server/src/browser/mediaEND_MARKER
root ➜ / $ code-server
[2024-12-09T14:23:39.397Z] info  Wrote default config file to /root/.config/code-server/config.yaml
[2024-12-09T14:23:39.618Z] info  code-server 4.95.3 b0c935a6e0742adde9f7a5f6e5816553ee0e7ffb
[2024-12-09T14:23:39.620Z] info  Using user-data-dir /root/.local/share/code-server
[2024-12-09T14:23:39.631Z] info  Using config file /root/.config/code-server/config.yaml
[2024-12-09T14:23:39.631Z] info  HTTP server listening on http://127.0.0.1:8080/
[2024-12-09T14:23:39.631Z] info    - Authentication is enabled
[2024-12-09T14:23:39.631Z] info      - Using password from /root/.config/code-server/config.yaml
[2024-12-09T14:23:39.631Z] info    - Not serving HTTPS
[2024-12-09T14:23:39.631Z] info  Session server listening on /root/.local/share/code-server/code-server-ipc.sock
```

It looks like it mig like it might be an issue with my netwoht be an issue with my network. Is there a way for me to set up a proxy for creating gitspaces in the harness configuration?

**Comment by dhruv-harness** [comment]
Thanks for sharing the detailed output @zyknow . 

You are correct, the issue is with your networking. In the current release, there is no way to define any env variables such as proxies for individual gitspaces. 

There are a few methods available to set the proxy inside Docker config. Please check this. https://www.baeldung.com/ops/docker-setting-proxy#overview-2

Also, please note, the upcoming release for harness will have support for the `containerEnv` and the `runArgs` devcontainer spec properties, both of which can be used to set env variables for the container.

**Comment by zyknow** [comment]
Thank you @dhruv-harness for your help setting up the Docker proxy. I retested the command `curl -fsSL https://code-server.dev/install.sh | sh` and confirmed that the proxy is working. However, I am still encountering the same error.
```
260 2024/12/10 10:53:17  {"status":"Pull complete","progressDetail":{},"id":"b8ac462c08b2"}
261 2024/12/10 10:53:17  {"status":"Digest: sha256:9f2c0dc53f039379b9734d8f8d36ebdad9ee9a9a77c49f9df9b9ba1be871fc0d"}
262 2024/12/10 10:53:17  {"status":"Status: Downloaded newer image for mcr.microsoft.com/devcontainers/base:dev-ubuntu-24.04"}
263 2024/12/10 10:53:17  Successfully pulled image
264 2024/12/10 10:53:17  Creating container: gitspace-harness-tvnotice-19x34w
265 2024/12/10 10:53:18  Starting container: gitspace-harness-tvnotice-19x34w
266 2024/12/10 10:53:18  Successfully started container
267 2024/12/10 10:53:18  Managing user output...
268 2024/12/10 10:53:18  Setting up user inside container
269 2024/12/10 10:53:18  Successfully setup user
270 2024/12/10 10:53:18  Setting up IDE inside container: vs_code_web
271 2024/12/10 10:53:20  Error while setting up IDE inside container: media folder path should not be empty, VSCode web is not installed
```

**Comment by dhruv-harness** [comment]
@zyknow , upon further debugging, I found out that the proxies set through the config.json file are used by the docker cli (client), but not by the golang sdk client, which we use. Essentially, to set the proxies inside the container, env variables have to be passed. docker cli also does this, it reads the proxies and passes those as env variables.

I am not sure if there is any other way to set env variables as of now. The gitspace container needs access to internet to setup the tools required for development.

This will be supported in the upcoming release.

**Comment by dhruv-harness** [comment]
Hi @zyknow, please try out the latest release of the harness open source. It includes support for the `containerEnv` and the `runArgs` devcontainer spec properties, which should solve your use-case.

**Comment by zyknow** [comment]
@dhruv-harness I created and set up .devcontainer/devcontainer.json file and encountered an error.

`failed to read or parse devcontainer config: failed to parse devcontainer JSON: invalid character '\n' in string literal`
![image](https://github.com/user-attachments/assets/8d1693fd-50d1-49a6-ac2b-1a07b52292bc)


```json
{
  "containerEnv": {
    "HTTP_PROXY": "http://192.168.0.1:7893",
    "HTTPS_PROXY": "http://192.168.0.1:7893"
  }
}
```



I am unsure of how this error occurred. I tried changing the encoding, adjusting the line endings to LF or CRLF, and verifying the JSON format.

**Comment by dhruv-harness** [comment]
Hi @zyknow 
Please use the image `harness/harness:3.1.1`. This issue has been recently fixed.

**Comment by zyknow** [comment]
@dhruv-harness thanks, it's worked!
